### PR TITLE
Better README

### PR DESCRIPTION
**Pull request by sam9032**
Hey there!

Since your answer on my issue #1 was really good why not use it as a first version for the README?

LG

### CODE REVIEW

**Comment by vimpostor** [comment]
I guess adding a preliminary Readme won't hurt and is better than no Readme.
Can you please add an extra line to your commit message, saying "Fixes #1"

**Comment by sam9032** [comment]
> I guess adding a preliminary Readme won't hurt and is better than no Readme. Can you please add an extra line to your commit message, saying "Fixes #1"

Added your requested line to support you in your laziness.

**Comment by vimpostor** [comment]
Am Tue, Apr 26, 2022 at 07:31:06AM -0700 schrieb sam:
>Added your requested line

Thanks but please add it in an extra line for the commit, not in the 
same line.

Also you now have three commits in your branch. The easiest way to fix 
this is like this:

```bash
git reset --hard 840afbe
EDITOR=vim git commit --amend # Here you can edit the commit message
git push --force-with-lease
```

Thanks!

**Comment by sam9032** [comment]
No, I won't do that!
It should work, even if it is the same line?

> Am Tue, Apr 26, 2022 at 07:31:06AM -0700 schrieb sam:
> Added your requested line
> Thanks but please add it in an extra line for the commit, not in the same line. Also you now have three commits in your branch. The easiest way to fix this is like this: ```bash git reset --hard [840afbe](https://github.com/vimpostor/copycat/commit/840afbeff42bc20bdba2eaebc31c89a38e2e5bdd) EDITOR=vim git commit --amend # Here you can edit the commit message git push --force-with-lease ``` Thanks!

**Comment by vimpostor** [comment]
>No, I won't do that!
>It should work, even if it is the same line?

It's not about whether it will work, it's just basic commit guidelines.

The subject of a commit contains only a brief description and is usually 
not longer than 50 characters. The rest belongs in the body, especially 
things like "Fixes" messages.

Your branch still contains 3 commits, you can easily squash them 
together with my above instructions. This is btw why I also prefer the 
UX of sending patches via mail over the horrendous UX of using Github 
PRs. This type of stuff would never happen if we used git as it was 
initially intended to be used.

**Review by vimpostor — CHANGES_REQUESTED** [review]
You still have an unnecessary merge commit in your branch.
Do you need any more git tech support?

**Review by vimpostor — APPROVED** [review]

**Comment by vimpostor** [comment]
Thanks for giving me access to your fork repository, I have fixed the git commits now myself!

**Comment by sam9032** [comment]
On Thu, 2022-04-28 at 03:46 -0700, Magnus Groß wrote:
> Thanks for giving me access to your fork repository, I have fixed the
> git commits now myself!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

There you go, thanks James!

**Comment by vimpostor** [comment]
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>
>There you go, thanks James!

Who is James?

**Pull request merged**
